kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-metering-multicloudui-operator
subjects:
- kind: ServiceAccount
  name: ibm-metering-multicloudui-operator
roleRef:
  kind: Role
  name: ibm-metering-multicloudui-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-metering-multicloudui-operator-cluster
  labels:
    app.kubernetes.io/instance: "ibm-metering-multicloudui-operator"
    app.kubernetes.io/managed-by: "ibm-metering-multicloudui-operator"
    app.kubernetes.io/name: "ibm-metering"
subjects:
- kind: ServiceAccount
  name: ibm-metering-multicloudui-operator
  namespace: ibm-common-services
roleRef:
  kind: ClusterRole
  name: ibm-metering-multicloudui-operator
  apiGroup: rbac.authorization.k8s.io
